### ISSUE TITLE
Hot reloading in development mode

### ISSUE THREAD

**Issue by alanzanattadev** [alanzanattadev/atom-molecule-dev-environment#28]
- [ ] React
- [ ] Redux Reducers
- [ ] Redux Actions
- [ ] Redux Middlewares
- [ ] Plugins

**Comment by Kendos-Kenlen** [comment]
Due to the fact that we run on top of Atom and not as a standalone application, it's hard (maybe impossible) to allow hot reloading of Molecule as we don't work directly with the electron stack and can't add dependencies into atom itself.

The best solution is to use atom' dedicated plugins to reload plugins in development mode, or interface reloading.

I think we can close this issue as it's not really something we can do in Molecule (not now at least).
